hangman_words = [
    "abandon", "abstract", "academy", "account", "accumulate", "accuracy", "acoustic", 
    "activate", "adventure", "aerospace", "agility", "algebra", "alliance", "alphabet", 
    "aluminum", "ambition", "analyze", "ancestor", "ancient", "anomaly", "antenna", 
    "antique", "anxiety", "apology", "aquatic", "archive", "argument", "arsenal", 
    "artistic", "assembly", "athletic", "atmosphere", "attitude", "audience", "authority", 
    "autonomy", "aviation", "backbone", "balance", "ballistic", "barbecue", "barricade", 
    "bizarre", "blossom", "boundary", "bravery", "bronze", "building", "bulletin", 
    "butterfly", "cabinet", "calcium", "calendar", "campaign", "capacity", "captain", 
    "capsule", "capture", "caravan", "cascade", "catalog", "category", "celestial", 
    "ceremony", "champion", "chaos", "charcoal", "chariot", "charming", "chemical", 
    "chronic", "citizen", "clarity", "climate", "cluster", "collapse", "colossal", 
    "comfort", "comet", "commerce", "compass", "comrade", "concept", "conflict", 
    "conquest", "conserve", "constellations", "contain", "contract", "contrast", 
    "convince", "coral", "corruption", "cosmic", "courage", "creativity", "crescent", 
    "criminal", "crystal", "cuisine", "currency", "curtain", "custody", "cyclone", 
    "dandelion", "deadline", "decent", "decibel", "dedicate", "dehydrate", "delegate", 
    "density", "desert", "destiny", "detonate", "diameter", "diligent", "dioxide", 
    "disaster", "discipline", "disguise", "disrupt", "distant", "distinct", "division", 
    "document", "domestic", "donation", "dormant", "drought", "duality", "dungeon", 
    "dynamic", "ecology", "economy", "education", "electric", "elegant", "element", 
    "elevate", "ellipse", "emphasis", "empower", "endeavor", "engineer", "enigma", 
    "enhance", "enormous", "enrich", "epicenter", "epidemic", "equality", "erosion"
]